# Generated by Django 4.0.4 on 2022-05-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_alter_banner_description'),
        ('users', '0005_alter_user_batch_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commons.region'),
        ),
    ]
